from addons.date_time_operations import DateTimeOperations
from addons.file_uploader import FileUploader
from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
from src.testproject.sdk.drivers.actions import Actions
import pytest


"""
    Project: Android Happin
    Package: TestProject.Generated.Tests.AndroidHappin
    Test: Login test
    Generated by: David Ma (davidm989@gmail.com)
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="D1uRRn1VuaNoGGLrCu8YPWH00YOZaaApL-MJ6TcizbM",
                              project_name="Android Happin",
                              job_name="Login test")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://happin.app"
    CurrentDate = ""  # current date in dd/mm/yyyy format
    eventStartTime = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login2'
    login2 = driver.find_element(By.XPATH,
                                 "//a[. = 'Login']")
    login2.click()

    # 3. Click 'Continue with email'
    continue_with_email = driver.find_element(By.XPATH,
                                              "//button[. = 'Continue with email']")
    continue_with_email.click()

    # 4. Type 'chumifyqa1@gmail.com' in 'email3'
    email3 = driver.find_element(By.XPATH,
                                 "//form//input[@placeholder = 'Enter your email to continue']")
    email3.send_keys("chumifyqa1@gmail.com")

    # 5. Click 'Continue2'
    continue2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Continue']")
    continue2.click()

    # 6. Type 'Hello123456' in 'password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Enter you password']")
    password.send_keys("Hello123456")

    # 7. Click 'Continue2'
    step_settings = StepSettings(timeout=25000)
    with DriverStepSettings(driver, step_settings):
        continue2 = driver.find_element(By.XPATH,
                                        "//button[. = 'Continue']")
        continue2.click()

    # 8. Pause for '6000'ms
    driver.pause(milliseconds=6000)

    # 9. Click 'DIV'
    # Click top right menu
    div = driver.find_element(By.XPATH,
                              "//app-happin-app-navigation/div[2]/div/div/div")
    div.click()

    # 10. Click 'Host Event'
    # Click Host Event to Enter Dashboard
    host_event = driver.find_element(By.XPATH,
                                     "//a[3][. = 'Host Event']")
    host_event.click()

    # 11. Pause for '3500'ms
    driver.pause(milliseconds=3500)

    # 12. Click 'Create Event1'
    # Click Create Event
    create_event1 = driver.find_element(By.XPATH,
                                        "//button[. = 'Create Event ']")
    create_event1.click()

    # 13. Click 'Continue'
    # Default Livestream Event Selected
    _continue = driver.find_element(By.XPATH,
                                    "//button[. = 'Continue']")
    _continue.click()

    # 14. Get current date
    step_output = driver.addons().execute(
        DateTimeOperations.currentdate(
            format="dd/MM/yyyy"))
    CurrentDate = step_output

    # 15. Type 'Test Live Stream {CurrentDate}' in 'Enter event name'
    # Add Event Name "Test Live Stream " + Date
    enter_event_name = driver.find_element(By.XPATH,
                                           "//input[@placeholder = 'Enter event name']")
    enter_event_name.send_keys(f'Test Live Stream {CurrentDate}')

    # 16. Type 'test event summary' in 'P'
    # Add Event Summary
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'tiny-angular_21855769521618327183557_ifr']|/html/body/app-root/nz-layout/nz-layout/app-dashboard/nz-layout/nz-content/app-create-live-event/div/main/div/div/div[2]/div[2]/div[2]/form/div/nz-form-item[3]/nz-form-control/div/span/editor/div/div[1]/div[2]/div[1]/iframe"))
    p = driver.find_element(By.XPATH,
                            "//p")
    p.send_keys("test event summary")

    # 17. Upload a file to a specific element identifies by XPath
    driver.addons().execute(
        FileUploader.uploadfilebyxpathaction(
            path="C:\\Users\\David Ma\\web-banner.jpg",
            xpath="//nz-upload/div/div/input"))

    # 18. Click 'Next'
    next = driver.find_element(By.XPATH,
                               "//button[. = 'Next']")
    next.click()

    # 19. Get current date
    step_output = driver.addons().execute(
        DateTimeOperations.currentdate(
            format="yyyy-MM-dd HH:mm:ss"))
    CurrentDate = step_output

    # 20. Set '1' hours to '{CurrentDate}'
    step_output = driver.addons().execute(
        DateTimeOperations.sethours(
            hours="1",
            originalDateTimeValue=f'{CurrentDate}',
            originalDateTimeFormat="yyyy-MM-dd HH:mm:ss",
            resultFormat=""))
    eventStartTime = step_output

    # 21. Click 'Select date'
    select_date = driver.find_element(By.XPATH,
                                      "//input[@placeholder = 'Select date']")
    select_date.click()

    # 22. Clear 'Select date1' contents
    select_date1 = driver.find_element(By.XPATH,
                                       "//div/input[@placeholder = 'Select date']")
    select_date1.clear()

    # 23. Type '{eventStartTime}' in 'Select date1'
    select_date1 = driver.find_element(By.XPATH,
                                       "//div/input[@placeholder = 'Select date']")
    select_date1.send_keys(f'{eventStartTime}')

    # 24. Click 'Ok1'
    ok1 = driver.find_element(By.XPATH,
                              "//a[. = ' Ok ']")
    ok1.click()

    # 25. Click 'Next1'
    next1 = driver.find_element(By.XPATH,
                                "//button[. = 'Next']")
    next1.click()

    # 26. Click 'Free Tickets'
    free_tickets = driver.find_element(By.XPATH,
                                       "//button[. = ' Free Tickets ']")
    free_tickets.click()

    # 27. Click 'Paid Tickets'
    paid_tickets = driver.find_element(By.XPATH,
                                       "//button[. = ' Paid Tickets ']")
    paid_tickets.click()

    # 28. Click 'Private Fan Meeting Room'
    private_fan_meeting_room = driver.find_element(By.XPATH,
                                                   "//button[. = ' Private Fan Meeting Room ']")
    private_fan_meeting_room.click()

    # 29. Click 'Next2'
    next2 = driver.find_element(By.XPATH,
                                "//button[. = 'Next']")
    next2.click()

    # 30. Click 'Save and Continue1'
    save_and_continue1 = driver.find_element(By.XPATH,
                                             "//button[. = 'Save and Continue']")
    save_and_continue1.click()

    # 31. Pause for '5000'ms
    driver.pause(milliseconds=5000)

    # 32. Click 'Presale & Public Sale'
    # Click to sale time to now
    presale_public_sale = driver.find_element(By.XPATH,
                                              "//li[. = 'Presale & Public Sale']")
    presale_public_sale.click()

    # 33. Click 'Set a specific time'
    set_a_specific_time = driver.find_element(By.XPATH,
                                              "//input[@placeholder = 'Set a specific time']")
    set_a_specific_time.click()

    # 34. Click 'selected date'
    # Click on selected date
    selected_date = driver.find_element(By.XPATH,
                                        "//div[@aria-selected = 'true']")
    selected_date.click()
